name: Test Style Dictionary PL

on: 
  pull_request:
    branches: [main]
    types: [closed]
jobs:
  install_style_dictionary:
    name: Install Style Dictionary
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Install Style Dictionary
        run: npm install -g style-dictionary
      - name: Build Style Dictionary Json
        run: cd examples/complete/ && style-dictionary build
      - name: Echo Completion
        run: echo  "Completion"
