name: Test Style Dictionary PL

on: 
  pull_request:
    branches: [main]
    types: [closed]
  issue_comment:
    branches: [main]
    types: [edited, created]
jobs:
  install_style_dictionary:
    name: Install Style Dictionary
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Install Style Dictionary
        run: npm install -g style-dictionary
      - name: Build Style Dictionary Json
        run: cd examples/complete/ && style-dictionary build
      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Generated Dictionary Auto-Commit
          branch: main
      - name: Publish to Artifactory
        uses: jfrog/setup-jfrog-cli@v3
        env:
          # JFrog platform url (for example: https://acme.jfrog.io) 
          JF_URL: ${{ secrets.JF_URL }}
          # JFrog Platform access token
          JF_ACCESS_TOKEN: ${{ secrets.JF_TOKEN }}
      - run: | 
          jf rt ping
          echo "test file " > test.txt
          export BUILD_NAME="my-build"
          export BUILD_MODULE="my-module"
          export BUILD_NUMBER="1"
          export PATH_TO_DIRECTORY="name/version/dates"
          jf rt upload "test.txt" dspoc-repository/$PATH_TO_DIRECTORY --build-name $BUILD_NAME --build-number $BUILD_NUMBER --module $BUILD_MODULE
