name: Test Style Dictionary PL

on: 
  pull_request_review_comment:
    types: [created]

jobs:
  install_style_dictionary:
    name: Install Style Dictionary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Install Style Dictionary
        run: npm install -g style-dictionary
      - name: Echo Completion
        run: echo  "Completion"
